import FWCore.ParameterSet.Config as cms
from DQMServices.Core.DQMEDHarvester import DQMEDHarvester

dtTnPEfficiencyClient = DQMEDHarvester("DTTnPEfficiencyClient",
                                       #Histogram names listed as "passProbeHistoName:failProbeHistoName"
                                       histoNames = cms.untracked.vstring("DT_nPassingProbePerCh_W-2:DT_nFailingProbePerCh_W-2",
                                                                          "DT_nPassingProbePerCh_W-1:DT_nFailingProbePerCh_W-1",
                                                                          "DT_nPassingProbePerCh_W0:DT_nFailingProbePerCh_W0",
                                                                          "DT_nPassingProbePerCh_W1:DT_nFailingProbePerCh_W1",
                                                                          "DT_nPassingProbePerCh_W2:DT_nFailingProbePerCh_W2",
                                                                          "RPC_nPassingProbePerRoll_Barrel_W-2:RPC_nFailingProbePerRoll_Barrel_W-2",
                                                                          "RPC_nPassingProbePerRoll_Barrel_W-1:RPC_nFailingProbePerRoll_Barrel_W-1",
                                                                          "RPC_nPassingProbePerRoll_Barrel_W0:RPC_nFailingProbePerRoll_Barrel_W0",
                                                                          "RPC_nPassingProbePerRoll_Barrel_W1:RPC_nFailingProbePerRoll_Barrel_W1",
                                                                          "RPC_nPassingProbePerRoll_Barrel_W2:RPC_nFailingProbePerRoll_Barrel_W2",
                                                                          "RPC_nPassingProbePerRoll_Barrel_1D_W-2:RPC_nFailingProbePerRoll_Barrel_1D_W-2",
                                                                          "RPC_nPassingProbePerRoll_Barrel_1D_W-1:RPC_nFailingProbePerRoll_Barrel_1D_W-1",
                                                                          "RPC_nPassingProbePerRoll_Barrel_1D_W0:RPC_nFailingProbePerRoll_Barrel_1D_W0",
                                                                          "RPC_nPassingProbePerRoll_Barrel_1D_W1:RPC_nFailingProbePerRoll_Barrel_1D_W1",
                                                                          "RPC_nPassingProbePerRoll_Barrel_1D_W2:RPC_nFailingProbePerRoll_Barrel_1D_W2",
                                                                          "RPC_nPassingProbe_Barrel_allCh_1D:RPC_nFailingProbe_Barrel_allCh_1D",
                                                                          "RPC_nPassingProbePerRoll_Endcap_Sta-4:RPC_nFailingProbePerRoll_Endcap_Sta-4",
                                                                          "RPC_nPassingProbePerRoll_Endcap_Sta-3:RPC_nFailingProbePerRoll_Endcap_Sta-3",
                                                                          "RPC_nPassingProbePerRoll_Endcap_Sta-2:RPC_nFailingProbePerRoll_Endcap_Sta-2",
                                                                          "RPC_nPassingProbePerRoll_Endcap_Sta-1:RPC_nFailingProbePerRoll_Endcap_Sta-1",
                                                                          "RPC_nPassingProbePerRoll_Endcap_Sta1:RPC_nFailingProbePerRoll_Endcap_Sta1",
                                                                          "RPC_nPassingProbePerRoll_Endcap_Sta2:RPC_nFailingProbePerRoll_Endcap_Sta2",
                                                                          "RPC_nPassingProbePerRoll_Endcap_Sta3:RPC_nFailingProbePerRoll_Endcap_Sta3",
                                                                          "RPC_nPassingProbePerRoll_Endcap_Sta4:RPC_nFailingProbePerRoll_Endcap_Sta4",
                                                                          "RPC_nPassingProbePerRoll_Endcap_1D_Sta-4:RPC_nFailingProbePerRoll_Endcap_1D_Sta-4",
                                                                          "RPC_nPassingProbePerRoll_Endcap_1D_Sta-3:RPC_nFailingProbePerRoll_Endcap_1D_Sta-3",
                                                                          "RPC_nPassingProbePerRoll_Endcap_1D_Sta-2:RPC_nFailingProbePerRoll_Endcap_1D_Sta-2",
                                                                          "RPC_nPassingProbePerRoll_Endcap_1D_Sta-1:RPC_nFailingProbePerRoll_Endcap_1D_Sta-1",
                                                                          "RPC_nPassingProbePerRoll_Endcap_1D_Sta1:RPC_nFailingProbePerRoll_Endcap_1D_Sta1",
                                                                          "RPC_nPassingProbePerRoll_Endcap_1D_Sta2:RPC_nFailingProbePerRoll_Endcap_1D_Sta2",
                                                                          "RPC_nPassingProbePerRoll_Endcap_1D_Sta3:RPC_nFailingProbePerRoll_Endcap_1D_Sta3",
                                                                          "RPC_nPassingProbePerRoll_Endcap_1D_Sta4:RPC_nFailingProbePerRoll_Endcap_1D_Sta4",
                                                                          "RPC_nPassingProbe_Endcap_allCh_1D:RPC_nFailingProbe_Endcap_allCh_1D",
                                                                          "CSC_nPassingProbe_allCh:CSC_nFailingProbe_allCh",
                                                                          "CSC_nPassingProbe_allCh_1D:CSC_nFailingProbe_allCh_1D",
                                                                          "DT_nPassingProbe_allCh:DT_nFailingProbe_allCh"),
                                       diagnosticPrescale = cms.untracked.int32(1))
